    
#DataBase Console H2
spring:
    profiles: h2
  
    h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
    datasource:
      url: jdbc:h2:mem:todo;DB_CLOSE_ON_EXIT=FALSE   
    
# Jpa
    jpa:
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: create-drop
# jacson     
    jackson:
      date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
      time-zone: Asia/Seoul
 
---

spring:
  profiles: 
    active: h2
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false